### ISSUE TITLE
Chat text overflow

### ISSUE THREAD

**Issue by superseva** [bithir/dragonbane-bithir-mod#2]
The text is not breaking and going outside of chat message
![chrome_2Qr5XutNOF](https://github.com/bithir/dragonbane-bithir-mod/assets/4093045/fe7f5b42-e656-4f38-9f94-7a401cf11749)
no other mods installed except the dragon bane official ones

**Comment by bithir** [comment]
Hmmm... Looks like the editor in Foundry snuck in a "white-space:pre" in the text. Grrrr... 

Will be sorted, I got some other changes too to push.
